version: 2
jobs:
  build:
    docker:
      - image: apicciau/texlive_ubuntu:latest

    steps:
      - checkout
      - run:
          name: Create the PDF
          command: |
            python compile.py pdf
            cp bibliography.pdf /tmp/
      - store_artifacts:
          path: /tmp/bibliography.pdf
